#!/usr/bin/env python3
"""Build employer-home-mobile.html — the dedicated MOBILE DESIGN of the
employer homepage (Scott, 25 Aug: "I don't want a responsive page. I want
actual mobile design for the home page. images fit for mobile.").

Input: the BUILT employer-home.html (run build-employer-home.py first).
Output: employer-home-mobile.html — same content, phone-first presentation:
  - the five event-type photos swap to purpose-cropped 4:5 mobile renditions
    (assets/employer-home/*-m.jpg) in taller frames, not the desktop 3:2 crops
  - the four How-It-Works step eyebrows (SET UP / REVIEW & CONFIRM / EVENT DAY
    / POST-EVENT) are visible on the phone (the desktop page hides them below lg)
  - product visuals already have mobile-specific captures (review-confirm) or
    fold to phone layouts (calendar mock, Interview Settings, analytics)
  - a review-only view toggle links back to the desktop page
Header/footer remain capture artifacts; production keeps the live site chrome
(see EMPLOYER-HOME-DEV-NOTES.md).
"""
import re, sys

W = "/Users/scottl./Desktop/jobfairx-marketing"
SRC = f"{W}/employer-home.html"
OUT = f"{W}/employer-home-mobile.html"
s = open(SRC, encoding="utf-8").read()
orig = len(s)
log = []

def sub(label, old, new, count=1, regex=False):
    global s
    if regex:
        s2, n = re.subn(old, new, s)
    else:
        n = s.count(old); s2 = s.replace(old, new) if n == count else s
    if n != count or count == 0:
        print(f"ABORT [{label}]: {n} matches, expected {count}"); sys.exit(1)
    s = s2; log.append((label, n))

# ── 1. Title marks the variant ───────────────────────────────────────────────
sub("title", "<title>Hiring Event Platform for Employers | JobFairX</title>",
    "<title>Hiring Event Platform for Employers | JobFairX (Mobile design)</title>")

# ── 2. Step eyebrows visible on the phone ────────────────────────────────────
sub("step eyebrows visible",
    'hidden lg:inline-block text-xs font-bold text-brand uppercase',
    'inline-block text-xs font-bold text-brand uppercase', count=4)

# ── 3. Event-type photos: 4:5 mobile crops in taller frames ──────────────────
for nm, mob in [("healthcare.d1574504.png", "healthcare-m.jpg"),
                ("diversity.af0ced6e.png", "diversity-m.jpg"),
                ("veteran.4e121597.png", "veteran-m.jpg"),
                ("tech.b663863c.png", "tech-m.jpg"),
                ("entry-level.ac5531c3.png", "entry-level-m.jpg")]:
    sub(f"photo {mob}", f"assets/employer-home/{nm}", f"assets/employer-home/{mob}")
sub("photo frames 3:2 -> 4:5", 'class="aspect-[3/2] overflow-hidden"',
    'class="overflow-hidden" style="aspect-ratio:4/5"', count=5)

# ── 4. Replace the desktop page's view toggle with the mobile page's own ─────
# (the desktop builder appends its toggle before </body>; this page is built
# FROM that output, so swap the states and the link target)
if 'id="view-toggle"' in s:
    sub("view toggle -> mobile state",
        re.escape('<span style="color:#fff;background:#2563eb;border-radius:999px;padding:5px 12px">Desktop</span>'
        '<a href="mobile-view.html?page=employer-home-mobile.html" style="color:#cbd5e1;padding:5px 12px;text-decoration:none">Mobile</a>'),
        '<a href="employer-home.html" style="color:#cbd5e1;padding:5px 12px;text-decoration:none">Desktop</a>'
        '<span style="color:#fff;background:#2563eb;border-radius:999px;padding:5px 12px">Mobile</span>', regex=True)

# ── 5. Provenance ────────────────────────────────────────────────────────────
s = s.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n<!--\n"
  "  employer-home-mobile.html — the dedicated mobile design of the employer\n"
  "  homepage (generated by build-employer-home-mobile.py FROM the built\n"
  "  employer-home.html; never edit by hand). Phone-first presentation: 4:5\n"
  "  mobile photo crops, visible step labels, mobile product captures.\n"
  "  Header/footer: production keeps the live site's current chrome.\n-->\n", 1)

open(OUT, "w", encoding="utf-8").write(s)
print(f"{'label':<36} matches")
for l, n in log: print(f"  {l:<34} {n}")
print(f"\nchars {orig:,} -> {len(s):,}")
